consul:
    hostname: consul
    container_name: consul
    image: qnib/alpn-consul
    environment:
    - DC_NAME=dc1
    - CONSUL_BOOTSTRAP_EXPECT=1
    ports:
    - "8500:8500"
    dns: 127.0.0.1

zkui:
    hostname: zkui
    container_name: zkui
    image: qnib/alpn-zkui
    dns: 127.0.0.1
    environment:
    - DC_NAME=dc1
    links:
    - consul:consul
    ports:
    - 9090:9090
    privileged: true

zookeeper0:
    hostname: zookeeper0
    container_name: zookeeper0
    image: qnib/alpn-zookeeper
    dns: 127.0.0.1
    #volumes:
    #- opt/qnib/zookeeper/bin/:/opt/qnib/zookeeper/bin/
    environment:
    - DC_NAME=dc1
    - MYID=1
    #- START_ZOOKEEPER=false
    - SERVERS=zookeeper0.node.dc1.consul,zookeeper1.node.dc1.consul,zookeeper2.node.dc1.consul
    links:
    - consul:consul
    ports:
    - 2181:2181
    privileged: true

zookeeper1:
    hostname: zookeeper1
    container_name: zookeeper1
    image: qnib/alpn-zookeeper
    dns: 127.0.0.1
    environment:
    - DC_NAME=dc1
    - MYID=2
    - SERVERS=zookeeper0.node.dc1.consul,zookeeper1.node.dc1.consul,zookeeper2.node.dc1.consul
    links:
    - consul:consul
    privileged: true

zookeeper2:
    hostname: zookeeper2
    container_name: zookeeper2
    image: qnib/alpn-zookeeper
    dns: 127.0.0.1
    environment:
    - DC_NAME=dc1
    - MYID=3
    - SERVERS=zookeeper0.node.dc1.consul,zookeeper1.node.dc1.consul,zookeeper2.node.dc1.consul
    links:
    - consul:consul
    privileged: true
